### ISSUE TITLE
First time syncing takes ages

### ISSUE THREAD

**Issue by turanmahmudov** [turanmahmudov/PockIt2#1]
I receive messages from users that syncing takes hours. For me, first time syncing for 20 items with 12mbps internet speed (on Bq Aquaris e4.5) takes only 5 minutes. Background tasks are not allowed by Ubuntu, so I can't move syncing to the background. If you have a suggestion please comment here.

**Comment by krnekhelesh** [comment]
I have a couple of suggestion here to improve the startup time. First, when a user installs Pockit and logs in, he shouldn't be waiting long at all, it gives a bad impression. So for the first time sync,,

- Sync only the first 10-20 items and do the rest in the background when the user is reading through an article or the next time the app is opened.
- In Podbird, we download the podbird metadata like title, artist, description etc through XMLHttpRequest, but we download the Podcast cover art using the Ubuntu Download Manager. Cover arts are usually the heavy ones, so we push that to the background using Ubuntu Download Manager.

Hope this helps.

**Comment by turanmahmudov** [comment]
@krnekhelesh PockIt downloads all items with XhrHttpRequest. Syncing items takes nothing, but syncing articles takes long. Background syncing freezes the app. I have two ways:
- Sync only items first time, and enable to download articles when user wants
- Move syncing to WorkerScript (I don't know it would be good or not)
