### ISSUE TITLE
listitem swipe actions in light theme are barely visible

### ISSUE THREAD

**Issue by krnekhelesh** [turanmahmudov/PockIt2#24]
The contrast of the listitem swipe actions are low w.r.t to the light background and as a result are not visible clearly.

running on BQ, Nexus 4 rc-proposed channels.

**Comment by turanmahmudov** [comment]
@krnekhelesh can you please add screenshot?

**Comment by krnekhelesh** [comment]
![swipe](https://cloud.githubusercontent.com/assets/761845/14048389/3dd63d1c-f2ae-11e5-952e-4f62e47bcce8.png)

**Comment by turanmahmudov** [comment]
@krnekhelesh on bq e4.5 the background is white, can you help me to fix this?

**Comment by krnekhelesh** [comment]
I will look into it.
