### ISSUE TITLE
Keep screen on while performing full sync

### ISSUE THREAD

**Issue by krnekhelesh** [turanmahmudov/PockIt2#25]
As you mentioned, that PockIt gets suspended during full sync which essentially pauses the sync. I would recommend (as a temporary measure) to keep the screen always on and inform the user that sync only happens when pockit is open and while the sync is screen in on would help.

There is an apparmor permission allowing apps to keep screen on if that helps.

**Comment by turanmahmudov** [comment]
I don't want to keep screen open. If user forget to lock screen, the app would drain battery

**Comment by krnekhelesh** [comment]
No but that's the thing, if the user locks the screen, then your first time sync process is suspended as well which is bad for the user. The screen will be *only* on until the sync process is complete. After that you can turn the screen off. 

Keeping the screen on for a few minutes won't drain that much battery compared to the inconvenient freezing of the sync process where the user needs to keep the screen on by himself.

**Comment by turanmahmudov** [comment]
I added new commit. Please check it

**Comment by krnekhelesh** [comment]
Yup looks good. Nice work!
