### ISSUE TITLE
Add a settings option to sync when the app is opened

### ISSUE THREAD

**Issue by krnekhelesh** [turanmahmudov/PockIt2#28]
The Android Pocket client has this nice settings option to enable sync when the app is opened. This avoids users forgetting to sync, and at the same time keeps the default behaviour you have now intact.

**Comment by turanmahmudov** [comment]
"Auto sync" option in Settings does the same operation :) Now I noticed that it has bugs

**Comment by krnekhelesh** [comment]
Personally I think the wording "Auto Sync" is a bit ambiguous considering that it only does it on app startup or at random intervals. Perhaps renaming that to what the android app would be better.

**Comment by turanmahmudov** [comment]
Accepted! :)

**Comment by turanmahmudov** [comment]
@krnekhelesh what is the name of the option in Android?

**Comment by krnekhelesh** [comment]
The setting option in android is called "Sync when app opens" and has a checkbox next to it.

**Comment by turanmahmudov** [comment]
Fixed :)
