### ISSUE TITLE
Automatic sync stuck in loop

### ISSUE THREAD

**Issue by moritz-weber** [turanmahmudov/PockIt2#29]
When using automatic sync, the app gets stuck in a syncing loop:
First sync works as expected, but it keeps opening the sync dialogue (2x per second) and closes it immediately. Only way to get out is to press cancel (which is pretty hard, as the dialogue disappears very quickly).
I am using OTA 9.1 on a Nexus 7. Auto sync and download is enabled.

**Comment by turanmahmudov** [comment]
@moritz-weber this bug is fixed, new update will come soon
