### ISSUE TITLE
Add delete to context menu within article list

### ISSUE THREAD

**Issue by tstephen** [turanmahmudov/PockIt2#32]
The official client for android has Delete in addition to the options PockIt offers. It may appear this is not a big priblem but I somehow got into a situation that an article would only open in browser (it was a google search result if that suggests anything?) Consequently I had an article that could not be opened or archived forcing me back to android where I found the additional delete option.

**Comment by turanmahmudov** [comment]
Hi. In PockIt we have 2 types of context menus in articles list:
- Left swiping: Delete
- Right swiping: Share, Archive, Tag, Favorite

Are you talking about this?

**Comment by tstephen** [comment]
Ah! I hadnt noticed the left swipe for delete, under android all 5 options are under right swipe.Thanks. And thanks too for a great app.

I guess it's more a problem for Ubuntu than Pockit but some way (an overlay?) of discovering these options would be very helpful.
