### ISSUE TITLE
Don't include Pockit.pro.user file in the source tree

### ISSUE THREAD

**Issue by krnekhelesh** [turanmahmudov/PockIt2#9]
The Pockit.pro.user file is generated automatically on every developer's machine. It shouldn't be included in the source tree. I thought I had a pull request to remove it. But it is back again in the tree. Could you remove it pls?

**Comment by turanmahmudov** [comment]
Git doesn't listen to .gitignore. I deleted the file manually.

**Comment by krnekhelesh** [comment]
Hmm strange...looking at https://help.github.com/articles/ignoring-files/ it should work. Could it be that the first .pro.user file was added before the .gitignore file was added? Either way you could add *.pro to the .gitignore file and see if it there on ignores the file correctly?
